name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Upload html test report
        uses: actions/upload-artifact@v4
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  package:
    needs: [lint]
    name: Generate Signed APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Decrypt keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ci_cd_keystore.jks

      - name: Build signed APK
        run: |
          ./gradlew assembleRelease --stacktrace -Pandroid.injected.signing.store.file=ci_cd_keystore.jks.jks \
                                     -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
                                     -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
                                     -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: ci_cd_signed_build.apk
          path: app/build/outputs/apk/release/app-release.apk
